### ISSUE TITLE
virus in doc files

### ISSUE THREAD

**Issue by clearbrian** [dysbulic/tip#6]
Hi
I was testing new virus sw and it scanned an old copy of this repo from mar 2016 and theres viruses in the docs buried in it. i uses Avaast virus checker..

<img width="728" alt="avast mac securityscreensnapz001" src="https://user-images.githubusercontent.com/132359/28456229-8fea9a22-6df9-11e7-9e10-967dd34e1b21.png">

**Comment by dysbulic** [comment]
Yeah, those are design documents from a university class decades ago. No one ought to be opening them.

Also, it's a Word '97 macro virus, so it oughtn't affect anyone in any case.
